### PR TITLE
Add support for htmldjango in neovim

### PR DESCRIPTION
**Pull request by lcfd**
👋  Hi!

I'm trying to add support to the `htmldjango` filetype.
Let me know what you think about that. I'm new to Neovim.

### CODE REVIEW

**Comment by OkelleyDevelopment** [comment]
Hello @lcfd!  :wave: 
 
Depending on how things go today schedule wise, I should be able to review and test this evening. 

Just wanted to let you know *someone has seen the PR though* :sunglasses:

**Review by OkelleyDevelopment — APPROVED** [review]
### General Feedback

Awesome work, I find that having it specified both ways will reduce potential future issues trying to load these snippets. :sunglasses:  

### Regarding accessing the snippets

If you're attempting to load these snippets inside html files make sure to:

- Set the file type for html to be `djangohtml` (or `htmldjango`) via either:
  - `:set filetype=djangohtml` inside the editor
  - add the previous setting to your config

**OR** 
- Extend the snippets for `html` to include the `djangohtml` (See readme or wiki for a more verbose example)

I prefer the extension option, but I believe any of the methods above will accomplish the goal.

Going to merge this, however if you run into an issue with loading the snippets feel free to create an issue and tag me so we can sort it out further! :mechanical_arm:

**Comment by OkelleyDevelopment** [comment]
Additional note for anyone reading, 2 minutes after merging I discovered `:setfiletype` and after cycling through the types found Neovim has `htmldjango` included. 

I still believe this change is warranted because in my test for file types had set it as `djangohtml`, so having both mappings ensures people find the snippets!

**Comment by lcfd** [comment]
@OkelleyDevelopment Thank you for your work and advice!

Apparently, in Neovim the only way that Django templates are recognized is `htmldjango`.
In many other text editors and environments are recognized as `djangohtml` or even `djang-html`.
There is no clear standard name for this thing. This leads to many compatibility problems with libraries and snippets packages like this one.

> however if you run into an issue with loading the snippets feel free to create an issue

Sure! Thank you!

## The future

In the future would be nice to add also support for Jinja, which is different from Django templates.

## Maybe offtopic

The problem is always the filetype recognition, but I think I will work on some lps/plugin for Neovim in order to improve the situation. I think the filetype will be `htmljinja` but I'll come back when there will be updates.

**Pull request merged**
