### PR TITLE
Typo fixes for cppdoc

### PR DESCRIPTION
**Pull request by surmish**
summay -> summary
synonism -> synonym

### CODE REVIEW

**Comment by REmerald** [comment]
@surmish, I think it would be better to talk about this in the #327 with @Zeioth, so that they could make the pr like `fix(*doc) fix typos`.

Because it doesn't just affect one file (like 2 extra spaces only in cdoc.json), but all the *doc snippets. And making changes/improvements to one files, while ignoring the other could easily lead to chaos.

**Comment by Zeioth** [comment]
Ok I'm doing a quick "search and replace in project" for those typos. It's true it affects more languages.

**Comment by Zeioth** [comment]
@REmerald Fixed in #345. I've also fix the languages that have not been merged yet (ruby doc and kotlin doc)

**Comment by surmish** [comment]
Feel free to close this or merge it in the larger merge. I just happened to be using the cppdoc snippet at work yesterday and noticed this. Thanks for maintaining these amazing snippets✌️

**Pull request closed without merging**
