### PR TITLE
feat(zig): snippets

### PR DESCRIPTION
**Pull request by Eveeifyeve**
- Adds Simple [Zig][zigWebsite] Snippets

**Looking for recommendations to add more snippets** 

[zigWebsite]: https://ziglang.org/

### CODE REVIEW

**Comment by Eveeifyeve** [comment]
Zig users, let me know if you need more snippets.

**Comment by Eveeifyeve** [comment]
ops there the title is back

**Comment by Eveeifyeve** [comment]
Well since no one wanted added snippets, I am going to look for used things instead.

**Review by OkelleyDevelopment — CHANGES_REQUESTED** [review]
Hi @Eveeifyeve, appreciate the PR. 

Couple points:
- Could you `git rebase` on the latest main branch?
- Also the link in your description currently points to a 404 page

I think this is a solid start to support Zig snippets, just a few things to address before we can merge. :sunglasses:

**Comment by Eveeifyeve** [comment]
I have fixed the link I will do a git rebase when I have a chance

**Comment by Eveeifyeve** [comment]
I am currently out of town so I am not able to rebase the pr.

**Comment by Eveeifyeve** [comment]
I have rebased it and fixed the link.

**Comment by Eveeifyeve** [comment]
@OkelleyDevelopment do you want me to squash my commits or it's fine?

**Review by OkelleyDevelopment — APPROVED** [review]
@Eveeifyeve, up to you generally though if I see more than 10 commits I might ask for them to be condensed so it's easier to review. For the purpose of merging, I squashed the commits anyways so we're good for now. Thanks for the PR!

**Comment by Parsifa1** [comment]
image
i'm encountered error when using this :(

**Comment by Eveeifyeve** [comment]
> image i've encountered error when using this :(

Can you provide the line number, so I can make a pr to fix this snippet.

**Comment by Eveeifyeve** [comment]
> image i've encountered error when using this :(

Found the cause issue, fixed in #531. Sorry for the mess of prs, I to rename a branch and etc.

**Pull request merged**
