### PR TITLE
feat: add asciidoc snippets

### PR DESCRIPTION
**Pull request by t0mri**

### CODE REVIEW

**Comment by tigion** [comment]
Alternatively, I could also provide my [AsciiDoc snippets](https://github.com/tigion/dotfiles/blob/main/nvim/snippets/asciidoc.json) as a pull request.

They are mostly inspired by the [Asciidoctor documentation](https://docs.asciidoctor.org/asciidoc/latest/).

**Comment by t0mri** [comment]
thats great. so how it gonna be done?

im new to this pr stuffs. so you can contribute to this pr? or i should update my pr with your snippets?

**Comment by tigion** [comment]
I would clean up and complete my AsciiDoc snippets over the next few days and could then create a separate pull request.

**Comment by t0mri** [comment]
so can i withdraw this now?

**Pull request closed without merging**
