### PR TITLE
Add AdonisJS Edge Template Engine Snippets

### PR DESCRIPTION
**Pull request by jjdechavez**

### CODE REVIEW

**Review by OkelleyDevelopment — COMMENTED** [review]
Hey there @jjdechavez ! 

Everything looks ok to me on a first read through, though I am curious why only some have the `description` field? 

If you could elaborate on this, I'll do my best to get this merged in the next day or so. :sunglasses:

**Comment by jjdechavez** [comment]
Thank you for the feedback @OkelleyDevelopment

I just updated my commits on edge snippets! Looking forward to it

**Comment by OkelleyDevelopment** [comment]
Ah epic! I'll double check this evening :sunglasses:

**Review by OkelleyDevelopment — APPROVED** [review]
Awesome, thanks for contributing! :sunglasses:

**Pull request merged**
