### PR TITLE
fix(zig): Syntax error for zig snippets

### PR DESCRIPTION
**Pull request by burstknight**
A zig snippet has the syntax error. I try to fix it.

actions_error_log

### CODE REVIEW

**Comment by FObersteiner** [comment]
it seems #507 and #509 are duplicates of this - any chance of getting it merged?

**Review by jfrancai — APPROVED** [review]

**Review by edevil — APPROVED** [review]

**Comment by 0x546F6D** [comment]
> it seems #507 and #509 are duplicates of this - any chance of getting it merged?

#517 is the latest duplicate. Glad I could finally get rid of those annoying errors. +1 to the request of getting it merged.

**Comment by FObersteiner** [comment]
For the record, this PR has now been duplicated by #507, #509, #517 and #521. In general, it seems like a useful addition would be a test for valid json syntax in CI.

**Comment by Ren-B-7** [comment]
I believe there's still an error on the zig snippets  

```".name = \"${1}\"",```   

Isnt the comma missing before the end of qoutes?
Proposed should be more like  

```".name = \"${1}\",",```

Also would probably be better to split the commit from zig and cmake into 1 pr for each, higher chance of getting merged that way

**Comment by burstknight** [comment]
> I believe there's still an error on the zig snippets
> 
> `".name = \"${1}\"",`
> 
> Isnt the comma missing before the end of qoutes? Proposed should be more like
> 
> `".name = \"${1}\",",`
> 
> Also would probably be better to split the commit from zig and cmake into 1 pr for each, higher chance of getting merged that way

Thank, @Ren-B-7. I add the comma at the [line](https://github.com/burstknight/friendly-snippets/blob/5323c72cc6defe1435b31a2d9f1dd92eb21bccb7/snippets/zig.json#L20). 

I don't change cmake snippets for this pr, but I just change `package.json` for this pr because `package.json` of my fork conflicted with `rafamadriz/friendly-snippets`. Can you give me any suggestion?

**Comment by Eveeifyeve** [comment]
Superseeded by #530.

**Comment by OkelleyDevelopment** [comment]
Thanks for the PR @burstknight! However, I'm declining as #531 is merged and confirmed to be working as of my local testing. Please update any confirm as well, if any questions arise please leave a comment on an issue and I'll get back asap.

**Pull request closed without merging**
