### PR TITLE
change pinia vue to javascript

### PR DESCRIPTION
**Pull request by bobbyrahmanda13**
change pinia vue to javascript json because it doesn't work, and pinia uses js/ts not vue extension, Please check if there are errors, because I thought the ones in the vue folder worked for vue, js, and ts extensions, apparently not, those in the vue folder only worked for vue extensions.

i moved pinia to javascript for it to run

### CODE REVIEW

**Comment by OkelleyDevelopment** [comment]
Hello @bobbyrahmanda13 , could you link some of the resources you've referenced regarding pinia? 

 I think if we could see what you're looking, we would be better able to review these latest changes since there seems to be concern for potential errors.  
 
 Thanks :sunglasses:

**Comment by bobbyrahmanda13** [comment]
https://pinia.vuejs.org/core-concepts/#using-the-store
https://blog.logrocket.com/complex-vue-3-state-management-pinia/
https://codesource.io/introducing-pinia-vuejs-new-state-management-solution/
https://dev.to/carlomigueldy/getting-started-with-vue-3-pinia-store-typescript-by-building-a-grocery-list-app-19km
https://codesandbox.io/s/pinia-example-vcuiu

if my update is wrong it's ok close the request, and please help add some pinia snippets because vue no longer uses vuex as default state management, maybe that's the last vue snippet in my opinion because everything is very complete in my opinion compared to the vue snippet in vscode like this :
https://marketplace.visualstudio.com/items?itemName=sdras.vue-vscode-snippets
https://marketplace.visualstudio.com/items?itemName=hollowtree.vue-snippets

but there is still nuxt 3 that vue developers have been waiting for but we'll see :+1:

**Comment by bryant-the-coder** [comment]
@bobbyrahmanda13 can u help add? i am going to have an exam soon. @OkelleyDevelopment pls check

**Comment by OkelleyDevelopment** [comment]
@bobbyrahmanda13  My schedule has been kinda all over the place the last few weeks. I will try to give this a look as soon as I can. Don't think this should be too difficult to sort out :100:

**Pull request closed without merging**
