### PR TITLE
Bug fix: zig.json

### PR DESCRIPTION
**Pull request by FObersteiner**
there is an incorrectly escaped `"` in `zig.json` which can cause annoying error messages in nvim. See also https://ziggit.dev/t/did-i-mess-up-my-lazyvim-config/6325

### CODE REVIEW

**Comment by FObersteiner** [comment]
This has now been partly duplicated by #509 

Note: the repo does not specify a contribution/style guide (formatter to run etc.), so my editor auto-formatted the file with 2-spaces indentation.

**Comment by FObersteiner** [comment]
closing as duplicate of #504

**Comment by Dogacel** [comment]
It took me some time to reach here, so I support merging this ASAP 🙂.

**Comment by Eveeifyeve** [comment]
Superseeded by #531.

**Comment by OkelleyDevelopment** [comment]
@Dogacel @FObersteiner, if you pull in the latest changes from `main` it should be working properly now, will close the PR in the meantime. If any issues come up, please leave another message on the issue. Thanks!

**Pull request closed without merging**
