### PR TITLE
fix(c): remove redundant newline and fix `$0` position in `main` snippents

### PR DESCRIPTION
**Pull request by REmerald**
Kind of reverts 7a57697 and #443

The main point of not putting `$0` on newly indented line is because it's way easier for a user to press enter than pressing `esc` then `dd` if inserting `if` with empty `{}` was intended. See https://github.com/rafamadriz/friendly-snippets/pull/237#issuecomment-1427018361.

### CODE REVIEW

**Review by OkelleyDevelopment — APPROVED** [review]
This looks fine to me, but perhaps we can bring in some others so we're all on the same page since it's reverting some changes.

cc: @ilan-schemoul @rafamadriz

**Comment by OkelleyDevelopment** [comment]
Assuming there isn't any push back between now and the end of the week, I'll merge this PR then.

**Comment by surmish** [comment]
The `mainn` code snippet seems fine as is? It is a fairly common snippet and not having a newline adds unnecessary keystroke. The newline before `return EXIT_SUCCESS` seems like it should be retained too...

**Comment by OkelleyDevelopment** [comment]
Hi @REmerald, see the comment above. It might be the case we can decline this PR for now :thinking:

**Comment by REmerald** [comment]
@OkelleyDevelopment Other snippets with braces (if, switch, for, while, functions, struct) has been following this style for  1.5 years and everybody has been ok with it. Nobody changed them through pull requests, even @ilan-schemoul changed only these 2 and didn't touch other mentioned above.

So,
> It is a fairly common snippet and not having a newline adds unnecessary keystroke.

is not a valid argument, also for reasons explained in pr description.

> The newline before `return EXIT_SUCCESS` seems like it should be retained too...

Any logic behind this? Plus, many people use format-on-save and clang-format will remove it anyways if you don't have any code between the brace and the newline.

**Comment by ilan-schemoul** [comment]
> Kind of reverts [7a57697](https://github.com/rafamadriz/friendly-snippets/commit/7a5769713a400e408ad562d60abf6854fed3b9b5) and #443
> 
> The main point of not putting `$0` on newly indented line is because it's way easier for a user to press enter than pressing `esc` then `dd` if inserting `if` with empty `{}` was intended. See [#237 (comment)](https://github.com/rafamadriz/friendly-snippets/pull/237#issuecomment-1427018361).

I don't see the need for empty main but sure we can revert to be consistent

**Comment by REmerald** [comment]
> I don't see the need for empty main

It's for organizational purposes, the user may decide to write some functions before `main`, but still leave it empty, e.g. not to forget to write it afterwards.

> but sure we can revert to be consistent

@OkelleyDevelopment surmish put the thumbs-up emoji, so everybody seems to agree. Can it be merged now?

**Comment by ilan-schemoul** [comment]
> It's for organizational purposes, the user may decide to write some functions before main, but still leave it empty, e.g. not to forget to write it afterwards.

I really don't agree we should do everything according to a fringe case.
But again if it's a matter of consistency and habits we can revert.

**Comment by OkelleyDevelopment** [comment]
Thanks everyone for your input!

I will merge this PR for the consistency as the repo stands. 

Going forward, perhaps we should apply a higher level of scrutiny regarding the structure of snippets being added/modified to avoid similar discrepancies from reoccurring :thinking:

**Pull request merged**
