### PR TITLE
Add 2 Python Snippets to include return type annotation

### PR DESCRIPTION
**Pull request by OkelleyDevelopment**
Looking into issue #124, I realized we could just copy the current snippets and append on the return type annotation. 

So now it would look like this when selecting the snippet for the return type: 
image

The one above it in the picture is the original snippet already in the snippet collection. A similar approach was done for the methods snippet.

As always, I am open to input from others :sunglasses:

### CODE REVIEW

**Comment by OkelleyDevelopment** [comment]
All good @bryant-the-coder And yeah looking back I like this idea. Will push some updates shortly !

**Comment by bryant-the-coder** [comment]
> 

sorry for the late reply. appreciate your work

**Comment by OkelleyDevelopment** [comment]
image

The fix was to change the method and function snippets to have a "t" on the end to indicate the difference from the method / function snippets and the ones with return type included in the snippet.

**Comment by bryant-the-coder** [comment]
MERDGED!! Nice job @OkelleyDevelopment

**Pull request merged**
