### PR TITLE
Add basic rails snippet

### PR DESCRIPTION
**Pull request by marcushwz**
Hi, I added some `Rails` snippets that I usually use. This is not everything yet, I might slowly add in more when I come across other useful snippets.

I raised an [issue](https://github.com/rafamadriz/friendly-snippets/issues/15) earlier, and attempted to fix it in this PR as well. I am not sure whether the fix is okay. Let me know if need more testing or have any better solution. Thanks for this plugin btw :) Was searching for a snippet to use with `compe` and found `vimsnip` and `friendly-snippets` the easiest to setup.

### CODE REVIEW

**Comment by rafamadriz** [comment]
Hey thanks for contributing. I don't like the idea of removing the javascript snippets for javascriptreact and also typescript(react), as explained [here](https://github.com/rafamadriz/friendly-snippets/issues/15#issuecomment-841595814), they are still useful for those languages. I'm gonna get the snippets you added and try to find a work around for your issue #15.

Thanks once again for contributing.

**Comment by marcushwz** [comment]
Ohh okay, didn't know that there are shared snippets. Okay, it seems like it is not reading the `typescript.json` when I include `typescript` in the languages section which is pointing to `javascript.json`. I am really not sure why, it works when I install the original plugin, but not working when I point it to the local version. I will still try to figure it out at the same time, let me know if you find a workaround. Thanks!

**Comment by rafamadriz** [comment]
Hey just tested and can't reproduce your issue #15, Could you revert the `package.json` and not delete the javascript snippets for        `typescript`, `javascriptreact` and `typescriptreact` to merge ?

**Comment by marcushwz** [comment]
@rafamadriz Hi, I have added back `typescript and `typescriptreact` into the `package.json`

**Pull request merged**
